### ISSUE TITLE
Dataset resources

### ISSUE THREAD

**Issue by yamseyoung** [hjian42/LegalStories#1]
Hi there, I've read your terrific work! And I am interested in your dataset a lot. 
Since you have put this repository url for both code and data in the preprint's footnote, I am wondering will you make this dataset public in the future? Or if anybody wishes to have access to the dataset, a permission should be granted? 

Thanks so much!

**Comment by hjian42** [comment]
Hi, we we will post the code and dataset on this github in 2-3 weeks. Please stay tuned.

**Comment by yamseyoung** [comment]
> Hi, we we will post the code and dataset on this github in 2-3 weeks. Please stay tuned.

That's great. Thank you!

**Comment by hjian42** [comment]
@yamseyoung Hi, sorry for the delay. The code is recently published in the repository!
